title: MerLean
description: An Agentic Framework for Autoformalization in Quantum Computation
baseurl: ""
url: "https://doxtor6.github.io/MerLean-examples"
github_username: doxtor6
repository: doxtor6/MerLean-examples

exclude:
  - Gemfile
  - Gemfile.lock
  - serve.py
  - vendor

plugins:
  - jekyll-seo-tag
