title: MerLean
description: An Agentic Framework for Autoformalization in Quantum Computation
baseurl: ""
url: "https://arthurmerlean.com"
image: /assets/img/MerLean_logo.png
github_username: doxtor6
repository: doxtor6/MerLean-examples

exclude:
  - Gemfile
  - Gemfile.lock
  - serve.py
  - vendor

plugins:
  - jekyll-seo-tag
